version: "3.1"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/problems
      - ./cookie.jar:/root/.local/share/online-judge-tools/cookie.jar
